force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/Id_SubTodo_from_another_org__c.field-meta.xml
<CustomField>
    <fullName>Id_SubTodo_from_another_org__c</fullName>
    <label>Id SubTodo from another org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Create_for_test__c.field-meta.xml
<CustomField>
    <fullName>Create_for_test__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if testing</description>
    <label>Create for test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Id_Todo_from_another_org__c.field-meta.xml
<CustomField>
    <fullName>Id_Todo_from_another_org__c</fullName>
    <description>Id recieved from anothe org as a result of integration</description>
    <label>Id Todo from another org</label>
    <length>180</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestClasses/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static TestTodoFactory TODO = new TestTodoFactory();
    public static TestSubTodoFactory SUBTODO = new TestSubTodoFactory();

    public class TestTodoFactory {
        public Todo__c createDummyTodo(String name, Date deadline, Boolean isdone, Id anotherOrgId, Boolean needInsert){
            Todo__c todo = new Todo__c(Name = name, Deadline__c = deadline, isDone__c = isdone, Id_Todo_from_another_org__c = anotherOrgId, Create_for_test__c = true);
            if(needInsert) insert todo;
            return todo;
        }

        public List<Todo__c> createDummyListOfTodos(Integer count, String name, Date deadline, Boolean isdone, Id anotherOrgId, Boolean needInsert){
            List<Todo__c> todosList = new List<Todo__c>();
            for(Integer i = 0; i < count; i++){                
                todosList.add(createDummyTodo(name + ' ' + String.valueOf(i), deadline, isdone, anotherOrgId, needInsert));
            }
            if(needInsert) insert todosList;
            return todosList;
        }
    }

    public class TestSubTodoFactory {
        public SubTodo__c createDummySubTodo(String name, Boolean isdone, Id anotherOrgId, Id todos, Boolean needInsert){
            SubTodo__c stodo = new SubTodo__c(Name = name, isDone__c = isdone, Id_SubTodo_from_another_org__c = anotherOrgId, Todo__c = todos);
            if(needInsert) insert stodo;
            return stodo;
        }

        public List<SubTodo__c> createDummyListOfSubTodos(Integer count, String name, Boolean isdone, Id anotherOrgId, Id todos, Boolean needInsert){
            List<SubTodo__c> stodosList = new List<SubTodo__c>();
            for(Integer i = 0; i < count; i++){                
                stodosList.add(createDummySubTodo(name + ' ' + String.valueOf(i), isdone, anotherOrgId, todos, needInsert));
            }
            if(needInsert) insert stodosList;
            return stodosList;
        }
    }
}