force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Auto-formula for category of Todo</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Id_Todo_from_another_org__c.field-meta.xml
<CustomField>
    <fullName>Id_Todo_from_another_org__c</fullName>
    <description>Id recieved from anothe org as a result of integration</description>
    <label>Id Todo from another org</label>
    <length>180</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/classes/DeletingOldTodoWithCMT.cls
global without sharing class DeletingOldTodoWithCMT implements Database.Batchable<Todo__c>{
    global Iterable<Todo__c> start(Database.BatchableContext bc) { 

        Date myDate = setCreationDateForQuering('Three');
        List<Todo__c> listTodos= [SELECT Id, Name, Category__c, Completion_Date__c, Deadline__c,
        Id_Todo_from_another_org__c, CreatedDate FROM Todo__c WHERE CreatedDate <=: myDate];
        return listTodos;
    }

    global void execute(Database.BatchableContext bc, List<Todo__c> scope){
        
        List<SubTodo__c> subTodoForDelete = new List<SubTodo__c>();
        
         
        Map<Id,Todo__c> todoMap = new Map<Id,Todo__c>(scope);
        if(scope.size() > 0){
            subTodoForDelete = [SELECT Id, Name FROM SubTodo__c WHERE Todo__c IN: todoMap.keySet()];
        } 
        if(subTodoForDelete.size() > 0) delete subTodoForDelete;
        if(scope.size() > 0) delete scope;
    }

    global void finish(Database.BatchableContext bc){
        System.debug('Batch Ok ' + bc.getJobId());
    }

    private static Date setCreationDateForQuering(String nameCMT){
        Map<String, Frequency_of_Todo_deletion__mdt> mapCMD = Frequency_of_Todo_deletion__mdt.getAll();
        Integer countMonth = (Integer)mapCMD.get(nameCMT).Month__c;
        Date todayDay = date.today();
        Date myDate = todayDay.addMonths(-countMonth);
        return myDate;
    }
}