force-app/main/default/objects/ToDo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Auto-formula for category of Todo</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to take</fullName>
                <default>true</default>
                <label>Ready to take</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoController.cls
public with sharing class ToDoController {
    @AuraEnabled
    public static List<ToDo__c> getTodolistForCategory() {
        Id userId = UserInfo.getUserId();
        return [
            SELECT Id, Name, Status__c, Deadline__C, OwnerId, Category__c
            FROM ToDo__c
            WHERE OwnerId != :userId
        ];
    }
    @AuraEnabled
    public static List<ToDo__c> getCurrentUserTodolist() {
        Id userId = UserInfo.getUserId();
        return [
            SELECT Id, Name, Status__c, Deadline__C, OwnerId, Category__c
            FROM ToDo__c
            WHERE OwnerId = :userId
        ];
    }
}