force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to take</fullName>
                <default>true</default>
                <label>Ready to take</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/classes/CreateTodoFromCase.cls
public with sharing class CreateTodoFromCase {

    public static void createTodo(List<Case> cs) {
        List<ToDo__c> newtd = New List<ToDo__c>();
        Date myDate = null;
        
        for(Case c : cs)
        {   
            try{
                myDate = Date.valueOf(c.Description);
            } catch (Exception e){
                myDate = Date.today();
            }  
            ToDo__c td = New ToDo__c(Name = c.Subject, Status__c = 'Ready to take', Deadline__c = myDate);
            newtd.add(td);    
        }
        insert newtd;
    }
}

//test 100%