force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to take</fullName>
                <default>true</default>
                <label>Ready to take</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo_Clear_Configuration__mdt/ToDo_Clear_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>ToDo Clear Configuration</label>
    <pluralLabel>ToDo Clear Configuration</pluralLabel>
</CustomObject>

force-app/main/default/objects/ToDo_Clear_Configuration__mdt/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ToDoClearingBatch.cls
public class ToDoClearingBatch implements Database.Batchable<SObject> {
    public final Integer months;
    public final Date deletingDate;
    public ToDoClearingBatch() {
        months = (Integer)ToDo_Clear_Configuration__mdt.getInstance('Number_Of_Months').Month__c;
        deletingDate = Date.today().addMonths((-1)*months);
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name, CreatedDate, Status__c, Deadline__c, '
        +'Completion_Date__c, IsDone__c, RecordTypeId, OwnerId FROM ToDo__c '
        +'WHERE CreatedDate <= :deletingDate');
    }
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<ToDo__c> todoListForDelete = (List<ToDo__c>)scope;
        if (todoListForDelete.size() != 0) {
            delete todoListForDelete;
        }
    }
    public void finish(Database.BatchableContext bc) {

    }
}